Feature/choojaeho/non login get
wecode-bootcamp-korea/37-1st-jeong6-jjeom-backend pull request #12
Opened 2022-09-24 08:29 UTC by JaeHoChoo

1. 비로그인 정보요청에 대한 api 입니다.

2. 그사이 머지된 내용이 있어서 클론을 다시받아 그전 수정사항들을 반영했습니다.
   - 필요없는 주석 제거
   - layer 파일명 categories -> product 로 수정

2022-09-26 01:12 UTC, bigfanoftim requested changes

2022-09-26 01:12 UTC, bigfanoftim commented on api/routes/productRouter.js
> +router.get('/getCategory', productController.getCategory)
이미 `HTTP Method(GET)`에 의미가 충분히 담겨 있기 때문에 endpoint 주소에 `get`을 작성하실 필요는 없을 것 같습니다. 
```suggestion
router.get('/categories', productController.getCategory)
```

다른 엔드포인트들도 수정해 주세요~

2022-09-26 01:12 UTC, bigfanoftim commented on api/models/productDao.js
> +const getCategoryId = async (categoriesId) => {
category_id를 가져오는 함수가 아니라 category_id를 가지고 product 데이터를 가져오는 함수로 보여집니다.
`getProductsByCategoryId`로 네이밍을 정확히 해주세요.

모든 함수가 동일한 상황이니 전부 수정해 주세요!

2022-09-26 07:52 UTC, JaeHoChoo commented
함수이름과 엔드포인트를 변경했습니다.

2022-09-26 08:32 UTC, bigfanoftim requested changes

2022-09-26 08:32 UTC, bigfanoftim commented on api/controllers/productController.js
> +    const { categoriesId, productId } = req.query
```suggestion
// endpoint -> GET :3000/products/:productId
    const { productId } = req.params
```

2022-09-26 08:32 UTC, bigfanoftim commented on api/controllers/productController.js
> +    const categoriesId = req.query.categoriesId
```JavaScript
// :3000/products?categoryId=1&typeId=2
const { categoryId } = req.query
```

2022-09-26 08:32 UTC, bigfanoftim commented on api/routes/productRouter.js
> +router.get('/description', productController.getProductByProductsId);
```suggestion
router.get('/:productId', productController.getProductByProductsId);
```

2022-09-26 08:32 UTC, bigfanoftim commented on api/routes/productRouter.js
> +router.get('/productDescription', productController.getDescriptionByProductId);
```suggestion
// GET :3000/products/1/description
router.get('/:productId/description', productController.getDescriptionByProductId);
```

2022-09-26 09:40 UTC, JaeHoChoo commented
알려주신 에러핸들링 아이디어에서 카트아이디 대신 미리 선언한 deletedRaws를 넣었습니다. 그외에 cartids로 모든 명칭을 바꿨습니다

2022-09-26 13:06 UTC, JaeHoChoo commented
1.짚어주신 restful API 를 위한 수정 완료 추가 수정사항 리뷰바랍니다.

2. Dao 에서 option product table 에서 thick 칼럼을 조회하기위해 쿼리문 수정
  이에 대하여 리뷰부탁드립니다.

2022-09-27 01:02 UTC, bigfanoftim approved these changes

2022-09-27 04:24 UTC, JaeHoChoo commented
해당 콘플릭트 해결 했습니다. 검토 부탁드립니다

2022-09-27 05:18 UTC, merged