feature/choojaeho/carts_delete
wecode-bootcamp-korea/37-1st-jeong6-jjeom-backend pull request #14
Opened 2022-09-25 09:24 UTC by JaeHoChoo

추가 구현 사항 및 리뷰 요청 부분

1. 컨트롤러 단에서 들어오는 쿼리문을 숫자일때와 배열로 들어올때를 구분하기 위하여 if문과 for문을 활요했습니다. 혹시 이부분을 줄일수 있는 방법이 있다면 힌트만 주시면 피드백 하겠습니다.

2022-09-26 01:16 UTC, bigfanoftim requested changes

2022-09-26 01:16 UTC, bigfanoftim commented on api/controllers/cartsController.js
> +    }
for문을 이용하여 넘겨받는 cartId에 따라 매번 DELETE문을 사용하는 것이 아닌
List로 넘겨받은 cartId를 전부 DELETE하는 방법으로 진행해 주세요!

제 생각으로는 작성하신 Dao라면 여러 데이터를 한번에 삭제할 수 있도록 잘 작성하신 것으로 보여집니다.

2022-09-27 04:36 UTC, JaeHoChoo commented
콘플릭트 해결하고 보냅니다

2022-09-27 10:47 UTC, JaeHoChoo commented
이전에 발생했던 푸시에러가 발생하여 -f를 사용하여 푸시했습니다.

2022-09-28 01:49 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-28 01:50 UTC, merged