order create 입니다.
wecode-bootcamp-korea/37-1st-jeong6-jjeom-backend pull request #20
Opened 2022-09-28 05:16 UTC by WJJayyy

order create입니다.

2022-09-28 08:05 UTC, bigfanoftim commented
우진님! 전체적으로 코드는 잘 작성해주셨으나 이런 상황에서 꼭 알고 계셔야 할 키워드가 있어 댓글에 남깁니다~

`주문(order)`을 하게되면 `orders`, `order_products`에 데이터가 생성이 되는데 서로 다른 테이블에 생성한다고 하여 endpoint를 나누게 되면 다음과 같은 문제가 발생합니다.
1. `orders` 데이터를 만들고 `order_products`에 `order_id`를 가져와 데이터를 만들다가 어떠한 이유로 실패
  - 이 경우 `orders` 테이블에 주문 데이터는 만들어졌으나 주문 상품은 하나도 등록되지 않았을 겁니다.
  - 이건 사용자의 비용과 관련된 부분으로 굉장히 민감한 부분이니 항상 신경써야 하는 에러 발생 예시입니다.

따라서 주문 API라고 한다면 `POST method` endpoint를 하나로 작성하여야 합니다. 하지만 여전히 위의 문제를 해결할 수는 없습니다.
이때 DB의 Transaction 기능을 이용해야 합니다.
`create order`, `create order_products`와 같은 여러 쿼리들을 각각 독립적인 작업으로 보는 것이 아니라 하나의 작업으로 묶어서 처리하도록 설정하여 여러 작업 중 하나라도 성공하지 못한다면 다시 이전의 상태로 돌아가는 개념이라고 보시면 됩니다.

저희는 현재 db 관련 패키지를 typeorm을 이용하고 있으므로 typeorm에서 지원해주는 `transaction`을 이용하면 됩니다.
1. `typeorm`의 `DataSource 객체 내 메소드 transaction()` 활용
2. `typeorm`의 `queryRunner` 활용

찾아 보시면 사용 방법은 금방 익히실 수 있을거에요! 슬랙을 남겼지만 답이 없으셔서 길게 텍스트로 남겨놓습니다~!!

2022-09-28 08:54 UTC, bigfanoftim commented
우진님! 오늘 저녁에 하시다가 궁금한 점이나 블로커 생기시면 여기 PR 커멘트로 남겨주시면 제가 시간날때 확인하겠습니다. 
- ex) queryRunner 혹은 transaction() 자체를 작성하지 못하겠습니다.
- ex) 트랜잭션 이해가 잘 되지 않습니다.

2022-09-28 14:00 UTC, WJJayyy commented
transaction 적용 및 delete 추가 하였습니다.

2022-09-29 02:03 UTC, bigfanoftim requested changes
잘 작성해 주셨습니다! 이름만 한번씩 수정해서 다시 푸시해 주세요 우진님!

2022-09-29 02:03 UTC, bigfanoftim commented on api/models/orderDao.js
> +const stockInOrder = async (optionProductsId, quantity) => {
```suggestion
const getStockOfOptionProduct = async (optionProductsId, quantity) => {
```
하고자 하는 행위, 데이터를 한눈에 파악할 수 있게 작성해 주세요!

2022-09-29 02:03 UTC, bigfanoftim commented on api/models/orderDao.js
> +const orderProductsOfOder = async (optionProductsId, orderId, quantity) =>{
```suggestion
const createOrderProducts = async (optionProductsId, orderId, quantity) =>{
```

2022-09-29 02:03 UTC, bigfanoftim commented on api/models/orderDao.js
> +const deliveryInformationOfOder = async (userId, name, phoneNumber, address, arrivalDate, deliveryMethod) => {
```suggestion
const createDeliveryInformation = async (userId, name, phoneNumber, address, arrivalDate, deliveryMethod) => {
```

2022-09-29 02:42 UTC, WJJayyy commented
변수이름 수정 하였습니다.
감사합니다!

2022-09-29 04:57 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-29 04:57 UTC, merged